spring:
  application:
    name: user-service
  data:
    rest:
      base-path: /api
  h2:
    console:
      enabled: true
server:
  port: 6786

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

